### ISSUE TITLE
black screen playing stream on https://b.siobud.com/(key here)

### ISSUE THREAD

**Issue by ian-kelling** [Glimesh/broadcast-box#108]
Sent video from obs, it didn't show any errors, showed connected and bitrate and everything looked good. I can record to file and it works. What is a good next step to figure out what went wrong? Run broadcast-box myself?

**Comment by Sean-Der** [comment]
Hey @ian-kelling 

Are you able to broadcast from your browser? `https://b.siobud.com/publish/(key here)`

What browser are you using? Do you know if H264 support is enabled/working? Might be worth trying temporarily a stock Google Chrome/FireFox

**Comment by Sean-Der** [comment]
Opening `chrome://webrtc-internals` is your best debugging tool. It shows how many video packets are flowing in etc...

**Comment by Sean-Der** [comment]
I am going to resolve @ian-kelling if you are still having issues I would love to help!

thanks

**Comment by SergeyKasmy** [comment]
I'm encountering the same issue, both with OBS and publishing via the site. Interestingly, OBS2Browser also stopped working...

I'm using Arch Linux, latest Firefox (also tested Chrome), latest broadcast-box docker container    
`docker run -e NETWORK_TEST_ON_START=false -e UDP_MUX_PORT=8080 -e NAT_1_TO_1_IP=127.0.0.1 -p 8080:8080 -p 8080:8080/udp --name broadcast-box --rm seaduboi/broadcast-box`

`about:webrtc-internals` in Chrome shows that packets are received, yet the media player is completely empty.

I have no idea what changed, everything worked before...

I commented here because this seems like the same issue to me. If needed, I can create a new one
