### ISSUE TITLE
Delay upto 10 secs after streaming for a few hours 

### ISSUE THREAD

**Issue by sharadagg** [Glimesh/broadcast-box#30]
I notice a delay of around 10 secs between the source and client side view. It started off fine.. but over 3 hours the delay got up tp 10 secs. Wonder if anyone else has noticed this.

I am using OBS 29.1.O-505-gdb8ae46ca (64 bit) to stream locally to broadcast-box 
I have 4 local viewers in chrome browsers and 1 local obs viewer (as browser source).

Will test it further to see how this delay builds up over 30 mins, 60 mins, 90 mins... 180 mins.

**Comment by sharadagg** [comment]
It happened in my test somewhere between 1hr 6 mins and 1hr 25 mins. See attached screenhsot. Before 1hr 6mins it was sub second latency.

![explorer_k0IBmPsNxz](https://github.com/Glimesh/broadcast-box/assets/81471321/539fc33a-bc08-4bbe-9887-203881130f14)

**Comment by Sean-Der** [comment]
That's an interesting one!

@sharadagg maybe we should add code that re-creates the PeerConnection on tab resumption? I don't know what control we have to reduce delay on the client side.

**Comment by makindotcc** [comment]
What about other (non chromium fork) browser like Firefox? It looks like some background tab throttling https://blog.chromium.org/2020/11/tab-throttling-and-more-performance.html because browser does the heavy lifting of playing livestream.
What happens when you pause video, (optionally) wait a few seconds and then play? Maybe browser would catch up to newer frames.

**Comment by Sean-Der** [comment]
I am going to resolve this for now. I am not able to reproduce it locally.

If others are having issues please reach out and happy to help :)
