### ISSUE TITLE
Attempting to deploy to GCP / Cloud Run

### ISSUE THREAD

**Issue by eheaton** [Glimesh/broadcast-box#40]
Has anybody had any success with this? I'm able to get the site working, along with all the WebRTC channels - however, OBS throws an error after about 15 seconds:

> WHIP :: SetRemoteDescription - Error! SetRemoteDescription called with no ice-ufrag

The Docker image works as it should when run locally, but not when deployed to CloudRun. Any help would be appreciated.

**Comment by Sean-Der** [comment]
Hi @eheaton!

It looks like Pion isn't able to gather any candidates. I have never used Cloudrun before, does it give you a public IP with UDP connectivity?

You can configured/influence the network configuration with this env variables.

* `INCLUDE_PUBLIC_IP_IN_NAT_1_TO_1_IP` - Auto attempt to determine your world routable IP
* `NAT_1_TO_1_IP` - Explicitly inform Pion about your world routable IP
* `INTERFACE_FILTER` - Only listen on one network interface
* `UDP_MUX_PORT` - Listen on a singular UDP Port (instead of all)
* `TCP_MUX_ADDRESS` - Listen on a singular TCP Port (by default TCP is off)

**Comment by Sean-Der** [comment]
Hi everyone. I have made a few changes/additions that I hope will help.

### Network Test on Startup

Broadcast Box will now make sure that connectivity is possible on startup. If your server is configured incorrectly it will tell you. You can read more about it [here](https://github.com/Glimesh/broadcast-box?tab=readme-ov-file#network-test-on-start) this will hopefully help people debugging more.

### Docker Compose with HTTPs

I have updated the docker-compose to use Caddy. All you need to do is set `URL` and everything will just work! https://github.com/Glimesh/broadcast-box?tab=readme-ov-file#docker-compose

----

@eheaton hopefully you got this working! If you are still having problems I would love to help.
